In [1]:
import os
import pandas

In [2]:
DATA_PATH_A = os.path.abspath("../../data/a.pkl.gz")
DATA_PATH_AC = os.path.abspath("../../data/ac.pkl.gz")
DATA_PATH_ACD = os.path.abspath("../../data/acd.pkl.gz")

dataA = pandas.read_pickle(DATA_PATH_A)
dataAC = pandas.read_pickle(DATA_PATH_AC)
dataACD = pandas.read_pickle(DATA_PATH_ACD)

In [3]:
dataA.head(7)

,patient_id,outcome_id,rhf,acpa,IgG_cit,IgG_arg_ctl,IgG_car,IgG_ace,IgG_lys_ctl,IgA_cit,IgA_arg_ctl,IgA_car,IgA_ace,IgA_lys_ctl
0,BF001,R,2.772589,5.831882,8.517073,2.028148,2.433613,1.526056,4.060443,1.722767,2.595255,0.641854,1.131402,0.641854
1,BF002,F,3.737670,5.337538,6.854882,1.887070,1.435085,1.902108,1.131402,0.788457,3.122365,1.609438,0.916291,1.098612
2,BF004,R,3.218876,0.875469,0.336472,1.887070,1.410987,2.332144,1.945910,1.386294,1.667707,1.609438,0.000000,1.098612
3,BF005,F,3.496508,4.795791,6.862339,1.960095,0.741937,2.332144,1.386294,0.916291,1.360977,1.360977,0.000000,1.223775
4,BF006,R,3.806662,4.969813,6.746412,2.397895,2.140066,2.541602,2.028148,1.757858,1.360977,2.302585,1.458615,2.332144
5,BF009,R,2.708050,0.693147,0.788457,2.091864,1.481605,2.388763,1.916923,1.526056,1.648659,2.174752,1.458615,1.791759
6,BF010,R,3.688879,5.831882,4.812997,1.193922,3.210844,2.388763,2.442347,1.722767,1.386294,1.987874,1.609438,2.054124

In [4]:
dataAC.head()

,age,das28,crp,esr,tjc28,sjc28,phghvas,ptghvas,rheumdrug_methotrexate,rheumdrug_sulfasalazine,...,acpa,IgG_cit,IgG_car,IgG_ace,IgG_lys_ctl,IgA_cit,IgA_arg_ctl,IgA_car,IgA_ace,IgA_lys_ctl
0,0.388889,0.117647,0.010610,0.000000,0.0,0.0,0.111111,0.066667,1,0,...,1.000000,0.970162,0.312745,0.118165,1.000000,0.129829,0.709678,0.000000,0.204718,0.177754
1,0.259259,0.375000,0.076923,0.163934,0.0,0.0,0.111111,0.066667,1,0,...,0.915234,0.778683,0.184423,0.174834,0.000000,0.000000,0.870028,0.202857,0.165795,0.304247
2,0.277778,0.330882,0.034483,0.098361,0.0,0.0,0.111111,0.266667,1,0,...,0.150118,0.027781,0.181326,0.239640,0.278080,0.083074,0.427513,0.202857,0.000000,0.304247
3,0.518519,0.595588,0.137931,0.032787,0.0,0.0,0.111111,0.288889,1,0,...,0.822340,0.779542,0.095347,0.239640,0.087022,0.017763,0.334204,0.150766,0.000000,0.338910
4,0.407407,0.889706,0.347480,0.262295,0.0,0.0,0.111111,0.444444,1,0,...,0.852180,0.766187,0.275021,0.271204,0.306157,0.134705,0.334204,0.348177,0.263924,0.645859

In [5]:
dataACD.head()

,acpa,IgG_cit,IgG_arg_ctl,IgG_car,IgG_ace,IgG_lys_ctl,IgA_cit,IgA_arg_ctl,IgA_car,IgA_ace,...,sjc28,phghvas,ptghvas,rheumdrug_hydroxychloroquine,rheumdrug_methotrexate,rheumdrug_sulfasalazine,smoking_current,smoking_exsmoker,smoking_neversmoked,sex_female
0,1.000000,0.970162,0.467829,0.312745,0.118165,1.000000,0.129829,0.709678,0.000000,0.204718,...,0.0,0.111111,0.066667,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.915234,0.778683,0.412609,0.184423,0.174834,0.000000,0.000000,0.870028,0.202857,0.165795,...,0.0,0.111111,0.066667,0.0,1.0,0.0,0.0,0.0,1.0,1.0
2,0.150118,0.027781,0.412609,0.181326,0.239640,0.278080,0.083074,0.427513,0.202857,0.000000,...,0.0,0.111111,0.266667,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.822340,0.779542,0.441192,0.095347,0.239640,0.087022,0.017763,0.334204,0.150766,0.000000,...,0.0,0.111111,0.288889,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.852180,0.766187,0.612551,0.275021,0.271204,0.306157,0.134705,0.334204,0.348177,0.263924,...,0.0,0.111111,0.444444,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [6]:
print(*dataA.columns, sep='\n')
print("#")
print(*dataAC.columns.difference(dataA.columns), sep='\n')
print("#")
print(*dataACD.columns.difference(dataAC.columns), sep='\n')

patient_id
outcome_id
rhf
acpa
IgG_cit
IgG_arg_ctl
IgG_car
IgG_ace
IgG_lys_ctl
IgA_cit
IgA_arg_ctl
IgA_car
IgA_ace
IgA_lys_ctl
#
age
crp
das28
esr
phghvas
ptghvas
rheumdrug_methotrexate
rheumdrug_sulfasalazine
sex_female
sjc28
smoking_current
smoking_exsmoker
smoking_neversmoked
tjc28
#
AGER
AGRP
ANGPT1
ANGPT2
AREG
BDNF
BMP7
BST2
C1QA
CALCA
CCL1
CCL11
CCL13
CCL14
CCL15
CCL16
CCL19
CCL2
CCL20
CCL21
CCL22
CCL23
CCL24
CCL25
CCL26
CCL27
CCL3
CCL4
CCL5
CCL7
CCL8
CD200
CD200R1
CD27
CD274
CD276
CD3E
CD4
CD40
CD46
CD70
CD80
CD83
CD93
CEACAM5
CHI3L1
CLEC4A
CNTF
CRP
CSF1
CSF1R
CSF2
CSF3R
CST7
CTF1
CTLA4
CX3CL1
CXADR
CXCL1
CXCL10
CXCL11
CXCL12
CXCL13
CXCL14
CXCL2
CXCL3
CXCL5
CXCL6
FASLG
FGF19
FGF2
FGF21
FLT1
FLT3LG
FLT4
FTH1
FURIN
GDF15
GDF2
GFAP
GRN
GZMA
GZMB
HAVCR1
HGF
HLA-DRA
ICAM1
ICOSLG
IFNA1; IFNA13
IFNA2
IFNB1
IFNG
IFNL2; IFNL3
IFNW1
IKBKG
IL10
IL10RB
IL11
IL12B
IL12RB1
IL13
IL13RA2
IL15
IL15RA
IL16
IL17A
IL17A|IL17F
IL17B
IL17F
IL17RA
IL17RB
IL18
IL18R1
IL19
IL1B
IL1R1
IL1R2
IL1RL1
IL1RN
IL2
IL20
IL22
IL24
IL27
IL2RA
IL2RB
IL33
IL34
IL36A
IL36B
IL36G
IL3RA
IL4
IL4R
IL5RA
IL6
IL6R
IL6ST
IL7
IL7R
IL9
IgG_arg_ctl
KDR
KITLG
KLRK1
KNG1
LAG3
LAMP3
LCN2
LGALS9
LIF
LILRB2
LTA
LTA|LTB
MERTK
MICA
MICB
MIF
MMP12
MMP3
MMP9
MPO
MUC16
NCR1
NGF
NTF3
OSM
OSMR
PDCD1
PDCD1LG2
PDGFB
PGF
PTX3
S100A12
S100A9
SCG2
SDC1
SELE
SELP
SIRPA
SLAMF1
SPP1
TAFA5
TEK
TGFB1
TGFB3
THBS2
THPO
TIMP1
TIMP2
TLR3
TNFRSF11A
TNFRSF11B
TNFRSF13B
TNFRSF13C
TNFRSF14
TNFRSF17
TNFRSF18
TNFRSF1A
TNFRSF1B
TNFRSF21
TNFRSF4
TNFRSF8
TNFRSF9
TNFSF10
TNFSF11
TNFSF12
TNFSF13
TNFSF14
TNFSF15
TNFSF18
TNFSF4
TNFSF8
TNFSF9
TREM1
TREM2
TSLP
VCAM1
VEGFA
VEGFC
VEGFD
VSNL1
WNT16
WNT7A
rheumdrug_hydroxychloroquine

In [7]:
print(dataA.shape)
print(dataAC.shape)
print(dataACD.shape)

(114, 14)
(114, 25)
(109, 247)

In [8]:
dataA.describe()

,rhf,acpa,IgG_cit,IgG_arg_ctl,IgG_car,IgG_ace,IgG_lys_ctl,IgA_cit,IgA_arg_ctl,IgA_car,IgA_ace,IgA_lys_ctl
count,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000
mean,2.828048,3.447766,3.949258,2.048996,2.306765,2.341694,2.133859,2.411118,1.960731,2.241842,1.630530,1.856877
std,1.998806,2.311765,2.873341,0.453231,1.446388,1.203059,0.474311,1.339551,0.562694,0.751574,1.043946,0.601400
min,0.000000,0.000000,0.095310,0.741937,0.000000,0.741937,1.131402,0.788457,0.262364,0.641854,0.000000,0.000000
25%,0.000000,0.741937,1.360022,1.791759,1.458615,1.469981,1.856298,1.404375,1.573771,1.740466,0.832909,1.504077
50%,3.525928,4.199441,3.153867,1.967088,1.816419,2.322388,2.066863,2.041220,1.980978,2.185988,1.774809,1.879436
75%,4.543912,5.707110,6.837615,2.216471,2.863251,2.744045,2.370244,2.853275,2.287433,2.711227,2.317437,2.259145
max,6.287859,5.831882,8.776090,3.387774,7.781472,7.377759,4.060443,7.984940,3.549617,5.411646,5.526647,3.610918